### PR TITLE
[geoclue-provider-mlsdb] add Europe

### PR DESCRIPTION
**Pull request by Nokius**
This is a squash of my europe branch.

[mlsdbtool] add Bounding Box for Albania

[mlsdbtool] add Bounding Box for Andorra

[mlsdbtool] add Bounding Box for Armenia

[mlsdbtool] add Bounding Box for Austria

[mlsdbtool] add Bounding Box for Azerbaijan

[mlsdbtool] add Bounding Box for Belarus

[mlsdbtool] add Bounding Box for Belgium

[mlsdbtool] add Bounding Box for Bosnia and Herz.

[mlsdbtool] add Bounding Box for Bulgaria

[mlsdbtool] add Bounding Box for Croatia

[mlsdbtool] add Bounding Box for Cyprus

[mlsdbtool] add Bounding Box for Czech Republic

[mlsdbtool] add Bounding Box for Denmark

[mlsdbtool] add Bounding Box for Estonia

[mlsdbtool] moved Bounding Box for Finland

[mlsdbtool] add Bounding Box for France

[mlsdbtool] add Bounding Box for Germany

[mlsdbtool] add Bounding Box for Greece

[mlsdbtool] add Bounding Box for Hungary

[mlsdbtool] add Bounding Box for Iceland

[mlsdbtool] add Bounding Box for Ireland

[mlsdbtool] add Bounding Box for Italy

[mlsdbtool] add Bounding Box for Latvia

[mlsdbtool] add Bounding Box for Lithuania

[mlsdbtool] add Bounding Box for Luxembourg

[mlsdbtool] add Bounding Box for Macedonia

[mlsdbtool] add Bounding Box for Malta

[mlsdbtool] add Bounding Box for Moldava

[mlsdbtool] add Bounding Box for Montenegro

[mlsdbtool] add Bounding Box for Netherlands

[mlsdbtool] add Bounding Box for Norway

[mlsdbtool] add Bounding Box for Poland

[mlsdbtool] add Bounding Box for Portugal

[mlsdbtool] add Bounding Box for Romania

[mlsdbtool] add Bounding Box for Serbia

[mlsdbtool] add Bounding Box for Slovakia

[mlsdbtool] add Bounding Box for Slovenia

[mlsdbtool] add Bounding Box for Spain

[mlsdbtool] add Bounding Box for Sweden

[mlsdbtool] add Bounding Box for Switzerland

[mlsdbtool] add Bounding Box for United Kingdom

[mlsdbtool] add Bounding Box for Ukraine

[mlsdbtool] add missing ;

[mlsdbtool] add Bounding Box for Georgia

[mlsdbtool] add Bounding Box for Kazakhstan

[mlsdbtool] add Bounding Box for Turkey

[mlsdbtool] add Bounding Box for Monaco

[mlsdbtool] add Bounding Box for Liechtenstein

[mlsdbtool] add Bounding Box for Gibraltar

[mlsdbtool] add Bounding Box for Faroe Islands

[mlsdbtool] add Bounding Box for Jersey

[mlsdbtool] moved Bounding Box of Kazakhstan

[mlsdbtool] add Bounding Box for Guernsey

[mlsdbtool] add Bounding Box for Aland Islands

[mlsdbtool] add Bounding Box for Isle of Man

[mlsdbtool] add Bounding Box for San Marino

[mlsdbtool] add Bounding Box for Kosovo

[mlsdbtool] fix typo in Bounding Box Moldova

[mlsdbtool] removed doubled Bounding Box of Italy

[mlsdbtool] fixing space issue in Bounding Box Bosnia and Herzegovina

[mlsdbdata] add updated cell informations for Aland Islands

[geoclue-providers-mlsdb][spec] add Aland Islands

[geoclue-provider-mlsdb][pro] add Aland Islands

[geoclue-providers-mlsdb][spec] remove folder 6 for Aland Islands

[mlsdbdata] add updated cell informations for Albania

[geoclue-providers-mlsdb][spec] add Albania

[geoclue-provider-mlsdb][pro] add Albania

[geoclue-providers-mlsdb][spec] remove folder 8 for Albania

[mlsdbdata] add cell informations for Andorra

[geoclue-providers-mlsdb][spec] add Andorra

[mlsdbdata] add cell informations for Armenia

[geoclue-providers-mlsdb][spec] add Armenia

[geoclue-provider-mlsdb][pro] add missing Andorra

[mlsdbdata] add cell informations for Austria

[geoclue-providers-mlsdb][spec] add Austria

[mlsdbdata] add cell informations for Azerbaijan

[geoclue-providers-mlsdb][spec] add Azerbaijan

[mlsdbdata] add cell informations for Belarus

[geoclue-providers-mlsdb][spec] add Belarus

[geoclue-providers-mlsdb][spec] fix typo

[mlsdbdata] add cell informations for Belgium

[geoclue-providers-mlsdb][spec] add Belgium

[mlsdbdata] add cell informations for Bosnia and Herzegovina

[geoclue-providers-mlsdb][spec] add Bosnia and Herzegovina

[mlsdbdata] add cell informations for Bulgaria

[geoclue-providers-mlsdb][spec] add Bulgaria

[mlsdbdata] add cell informations for Croatia

[geoclue-providers-mlsdb][spec] add Croatia

[geoclue-providers-mlsdb][spec] add Czech Republic

[mlsdbdata] add cell informations for Cyprus

[geoclue-providers-mlsdb][spec] add Cyprus

[mlsdbdata] add cell informations for Denmark

[geoclue-providers-mlsdb][spec] add Denmark

[mlsdbdata] add cell informations for Estonia

[geoclue-providers-mlsdb][spec] add Estonia

[mlsdbdata] add cell informations for Faroe Islands

[geoclue-providers-mlsdb][spec] add Faroe Islands

[mlsdbdata] add updated cell informations for Finland

[geoclue-providers-mlsdb][spec] moved Finland to Europe section

[mlsdbdata] add cell informations for France

[geoclue-providers-mlsdb][spec] add France

[mlsdbdata] add cell informations for Georgia

[geoclue-providers-mlsdb][spec] add Georgia

[mlsdbdata] add cell informations for Germany

[geoclue-providers-mlsdb][spec] add Germany

[mlsdbdata] add cell informations for Gibraltar

[geoclue-providers-mlsdb][spec] add Gibraltar

[mlsdbdata] add cell informations for Greece

[geoclue-providers-mlsdb][spec] add Greece

 [geoclue-providers-mlsdb] fix broken lines and reomove empty lines

[mlsdbdata] add cell informations for Guernsey

[geoclue-providers-mlsdb][spec] add Guernsey

[mlsdbdata] add cell informations for Hungary

[geoclue-providers-mlsdb][spec] add Hungary

[mlsdbdata] add cell informations for Iceland

[geoclue-providers-mlsdb][spec] add Iceland

[mlsdbdata] add cell informations for Ireland

[geoclue-providers-mlsdb][spec] add Ireland

[mlsdbdata] add cell informations for Isle_of_Man

[geoclue-providers-mlsdb][spec] fix typo in Ireland %package

[geoclue-providers-mlsdb][spec] add Isle_of_Man

[mlsdbdata] add cell informations for Italy

[mlsdbdata] add cell informations for Jersey

[geoclue-providers-mlsdb][spec] add Jersey

[mlsdbdata] add cell informations for Kazakhstan

[geoclue-providers-mlsdb][spec] add Kazakhstan

[mlsdbdata] add cell informations for Kosovo

[geoclue-providers-mlsdb][spec] add Kosovo

[mlsdbdata] add cell informations for Latvia

[geoclue-providers-mlsdb][spec] add Latvia

[geoclue-providers-mlsdb][spec] fix typo in Hungary %files

[geoclue-providers-mlsdb][spec] fix order for Gibraltar

[mlsdbdata] add cell informations for Liechtenstein

[geoclue-providers-mlsdb][spec] fix order for Liechtenstein

[mlsdbdata] fix typo in folder for Kosovo

[geoclue-providers-mlsdb][spec] add Lithuania

[mlsdbdata] add cell informations for Lithuania

[mlsdbdata] add cell informations for Luxembourg

[geoclue-providers-mlsdb][spec] add Luxembourg

[geoclue-providers-mlsdb][spec] remove doubbled Lithuania %files

[geoclue-providers-mlsdb][spec] remove Liechtenstein folder 5 %files

[mlsdbdata] add cell informations for Macedonia

[geoclue-providers-mlsdb][spec] add Macedonia

[mlsdbdata] add cell informations for Malta

[geoclue-providers-mlsdb][spec] add Malta

[mlsdbdata] add cell informations for Moldova

[geoclue-providers-mlsdb][spec] add Moldova

[mlsdbdata] add cell informations for Monaco

[geoclue-providers-mlsdb][spec] add Monaco

[mlsdbdata] add cell informations for Montenegro

[geoclue-providers-mlsdb][spec] add Montenegro

[mlsdbdata] add cell informations for Netherlands

[geoclue-providers-mlsdb][spec] add Netherlands

[geoclue-providers-mlsdb][spec] fix %files for Montenegro

[mlsdbdata] add cell informations for Norway

[geoclue-providers-mlsdb][spec] add Norway

[mlsdbdata] add cell informations for Poland

[geoclue-providers-mlsdb][spec] add Poland

[mlsdbdata] add cell informations for Portugal

[geoclue-providers-mlsdb][spec] add Portugal

[mlsdbdata] add cell informations for Romania

 [geoclue-providers-mlsdb][spec] add Romania

[mlsdbdata] add cell informations for San Marino

 [geoclue-providers-mlsdb][spec] add San Marino

[mlsdbdata] add cell informations for Serbia

 [geoclue-providers-mlsdb][spec] add Serbia

[geoclue-providers-mlsdb][spec] fix typo in San Marino %package

[mlsdbdata] add cell informations for Slovakia

[geoclue-providers-mlsdb][spec] add Slovakia

[geoclue-providers-mlsdb][spec] fix typo in Serbia %package %files

[mlsdbdata] add cell informations for Slovenia

[geoclue-providers-mlsdb][spec] add Slovenia

[mlsdbdata] add cell informations for Spain

[geoclue-providers-mlsdb][spec] add Spain

[mlsdbdata] add cell informations for Sweden

[geoclue-providers-mlsdb][spec] add Sweden

[mlsdbdata] add cell informations for Switzerland

[geoclue-providers-mlsdb][spec] add Switzerland

[geoclue-providers-mlsdb][spec] fix typo in Slovenia %package

[geoclue-providers-mlsdb][spec] fix typo in Spain %package

[geoclue-providers-mlsdb][spec] fix typo in Sweden %package

[mlsdbdata] add cell informations for Ukraine

[geoclue-providers-mlsdb][spec] add Ukraine

[geoclue-providers-mlsdb][spec] fix typo in Switzerland %package

[mlsdbdata] add cell informations for United Kingdom

[geoclue-providers-mlsdb][spec] add United Kingdom

[mlsdbdata] add cell informations Binary for San Marino

[geoclue-providers-mlsdb][spec] fix typo in Serbia %files

### CODE REVIEW

**Comment by Nokius** [comment]
As source for the Bounding Boxes of the country I used this [source] (https://gist.github.com/graydon/11198540) for some territory I used [isithackday.com/geoplanet-explorer](http://isithackday.com/geoplanet-explorer/index.php)

I hope that I was not  messing with the Boxes

**Comment by chriadam** [comment]
Thanks!

Before I merge this, I wonder if there's a better way to store binary data like this, than in a git repository, and instead just have the package .spec in git, which defines which binary data to pull in?

**Comment by chriadam** [comment]
Also, could you break it up into maybe 5 commits (related to specific subregions within Europe, perhaps) so that I can review in github?  Currently it touches too many files and github doesn't let me see the .spec or .pro changes etc.

**Comment by Nokius** [comment]
As discussed on irc with @chriadam 

a) an internal discussion will point out where the binary blobs are stored
b) when question a is solved we have sync about how to split the changes into a commit

**Comment by saukko** [comment]
How large is the whole mlsdb content? Couple of GB's? It really doesn't sound like sane idea to continue keeping this data in the git tree or later on the maintenance becomes a pain. Though when building the data needs to be available as during build network access is not guaranteed after downloading the sources.

**Comment by Nokius** [comment]
The binary blobs are for Europe plus India and Australia 389MB

> du -sh  mlsdbdata/ 389M	mlsdbdata

**Comment by Nokius** [comment]
after the discussion on irc the next step from my side is to remove the blobs from this PR and change the PR to just add the Boundary Boxes.

**Comment by Nokius** [comment]
I changed the PR to just add the Bounding Box for Europe

**Comment by chriadam** [comment]
LGTM, thanks!

**Pull request merged**
