### PR TITLE
[mlsdbtool] Add bounding boxes for Africa. Contributes to MER#1559

### PR DESCRIPTION
**Pull request by Nokius**
This PR is adding following country / areas:

Algeria, Angola, Benin, Botswana, Burkina Faso, Burundi, Cameroon, Canary Islands, Cape Verde, Central African Republic, Ceuta, Chad, Comoros, Congo, Democratic Republic of the Congo, Djibouti, Egypt, Equatorial Guinea, Eritrea, Ethiopia, Gabon, Gambia, Ghana, Guinea, Guinea-Bissau, Ivory Coast, Kenya, Lesotho, Liberia, Libya, Madagascar, Madeira, Malawi, Mali, Mauritania, Mauritius, Mayotte, Melilla, Morocco, Mozambique, Namibia, Niger, Nigeria, Reunion, Rwanda, Sao Tome and Principe, Senegal, Seychelles, Sierra Leone, Somalia, South Africa, South Sudan, Sudan, Swaziland, Tanzania, Togo, Tunisia, Uganda, Zambia, Zimbabwe

### CODE REVIEW

**Comment by chriadam** [comment]
I'm not certain whether the bounding box "contains()" algorithm works for boxes which include the equator or the zero-meridian.  That's why I added the lat/lon shift parameters, but I haven't done any testing to see a) if they're required, b) if so, how that should be set up.

I should have thought about that earlier, for e.g. England, France and Spain which also have the zero-meridian pass through them...

**Comment by Nokius** [comment]
Is there a way to test it with out being physical in this ares?

**Comment by chriadam** [comment]
Create a fictional country bounding box which extends from (-1.0, -1.0) to (1.0, 1.0).  Then create a fake mls.csv file with data for cell towers at the following locations:

(-0.99, -0.99)
(-2.0, -0.99)
(-0.99, -2.0)
(-2.0, -2.0)

(0.99, 0.99)
(2.0, 0.99)
(0.99, 2.0)
(2.0, 2.0)

(-0.99, 0.99)
(-2.0, 0.99)
(-0.99, 2.0)
(-2.0, 2.0)

(0.99, -0.99)
(2.0, -0.99)
(0.99, -2.0)
(2.0, -2.0)

Ensure that the output mlsdb.data files only contain the fake cell tower locations which definitely fall within the fictional country's bounds.

**Comment by chriadam** [comment]
Well, that should test prime meridian and equator behaviour.  It still won't prove that it contains() algorithm is sound near the poles, but I guess there aren't any cell towers near the poles which we need to worry about just yet.

**Comment by Nokius** [comment]
@chriadam I missed to pick you on irc this week. How to inspect the mlsdb.data?

**Comment by chriadam** [comment]
You can use the `geoclue-mlsdb-tool --query <locationId> <cellId> <mcc> <mnc> mlsdb.data` command (just ensure that the mlsdb.data file path is that of the generated mlsdb.data for the country with the (-1.0, -1.0, 1.0, 1.0) bounding box, and set the other parameters to whatever fake data for those fields you inserted into the fake mls.csv file you used to generate the mlsdb.data from.

**Comment by chriadam** [comment]
Line 138 of mlsdb tool's main.cpp shows the expected format of the mls.csv:

    // radio,mcc,net,area,cell,unit,lon,lat,range,samples,changeable,created,updated,averageSignal

Note that: "area"= locationId, "cell" = cellId, "mcc" = mcc, "net" = mnc.

So, the fake mls.csv could contain a line like:

     GSM,230,21,7,55,-2.0,-2.0,500,20,1,20161209T12:27:13.005Z,20161209T12:27:13.005Z,21

That would identify a GSM tower with mcc 230, mnc 21, locationId 7, cellId 55, and a lat/lon of -2.0,-2.0.  So, according to our country's bounding box, it should NOT be included!  So, if we run:

     geoclue-mlsdb-tool --query 7 55 230 21 fakecountry.data

then if the bounding box contains() algorithm worked properly, it should NOT return any result (since -2.0, -2.0 falls outside of the bounding box).

**Comment by chriadam** [comment]
According to Nokius' testing, the bounding box algorithm does correctly handle zero-meridian and equator crossings.  See https://gist.github.com/Nokius/02e2ecbb42c67475e1a74c3e44376b73 for results.

**Comment by chriadam** [comment]
Merged!  Thanks!

**Pull request merged**
